### ISSUE TITLE
Windows detects as trojan :stare:

### ISSUE THREAD

**Issue by Zetvue** [imbreydan/Feather-Client-Installer#1]
Uhhh???
"Trojan:Script/Wacatac.B!ml"

**Comment by heqkler** [comment]
Don't worry false positive 🤽🏻

**Comment by Zetvue** [comment]
You sure

**Comment by ghost** [comment]
I mean you can literally read the code and compile it yourself. It's not malicious lol

**Comment by Co18** [comment]
Prob a trojan cuz normal feather client dont get flagged as a virus xd

**Comment by killerwasgone** [comment]
> Prob a trojan cuz normal feather client dont get flagged as a virus xd

thats because its cracked, and i had that false positive "trojan" for many things that crack stuff

**Comment by killerwasgone** [comment]
also github blocks viruses

**Comment by Co18** [comment]
most stuff that are cracked and flagged as viruses spoof hardware uuid or other stuff 
i dont understand too much so idk lmfao

**Comment by MrAn0nym** [comment]
> I mean you can literally read the code and compile it yourself. It's not malicious lol

You can't… This "installer" is just downloading jars from dropbox links… And those dropbox links are in a pastebin

**Comment by MrAn0nym** [comment]
> also github blocks viruses

only if they are uploaded to github and obvious

**Comment by MrAn0nym** [comment]
> > Prob a trojan cuz normal feather client dont get flagged as a virus xd
> 
> thats because its cracked, and i had that false positive "trojan" for many things that crack stuff

it doesn't give you access to mc without paying, it just downloads the jars for you lol

**Comment by ghost** [comment]
```
https://www.dropbox.com/s/7r6r9u2k7ztvalv/1.8.9-forge1.8.9-11.15.1.2318-1.8.9.json?dl=1
https://www.dropbox.com/s/1huwik2dmkwoowf/feather-1.8.9.jar?dl=1
https://www.dropbox.com/s/8be8tz88vsjey96/natives.zip?dl=1
https://www.dropbox.com/s/twvnojway5sbi5v/1.8.9.zip?dl=1
https://www.dropbox.com/s/nrpknoml0rc3caw/libraries.zip?dl=1
```
idk why i commented this it just seems a tad weird. hosting on dropbox is fine anyway.

**Comment by MrAn0nym** [comment]
Funniest thing is that rehosting the jars isn't even necessary and prevents it from receiving updates… Or it is oc just malware. Who could've imagined xD

**Comment by imbreydan** [comment]
> Funniest thing is that rehosting the jars isn't even necessary and prevents it from receiving updates… Or it is oc just malware. Who could've imagined xD

get this, theres modifications we had to make to the jars to let ANYBODY launch feather 😱😱.

If we just download all the assets from 3rd parties, it would not launch. Thanks for showing you don't know whats going on though

**Comment by MrAn0nym** [comment]
You at max have to modify one file, not 5

**Comment by killerwasgone** [comment]
> it doesn't give you access to mc without paying, it just downloads the jars for you lol

thats funny because last time i checked, people call things for free that are meant to be paid is called cracked.
any questions?
you are literally spreading false information, you just came in this conversation just to spread false information because you think a little github file is gonna delete your entire system32 folder, think smarter next time.

**Comment by killerwasgone** [comment]
> > it doesn't give you access to mc without paying, it just downloads the jars for you lol
> 
> thats funny because last time i checked, people call things for free that are meant to be paid is called cracked. any questions? you are literally spreading false information, you just came in this conversation just to spread false information because you think a little github file is gonna delete your entire system32 folder, think smarter next time.

also you literally replied to a 23 day old conversation about some stupid little github jar file, please stop and get a better life.

**Comment by ghost** [comment]
If you're so hell bent on it being malicious, why not use an http debugger or a network monitoring tool like glasswire and tell me what suspicious connections it makes?

**Comment by imbreydan** [comment]
> because you think a little github file is gonna delete your entire system32 folder, think smarter next time.

what are you even saying bro?? i MADE THIS?? i am very aware its not malicious and i could care less how old this is. stay mad
