### ISSUE TITLE
Splash progress has detected an error

### ISSUE THREAD

**Issue by PiglinAvice** [imbreydan/Feather-Client-Installer#10]
The game crashed whilst initializing game
Error: SplashProgress has detected a error loading Minecraft.
Exit Code: -1

^ Crash reason

How to fix

**Comment by dyrkuwu** [comment]
same

**Comment by dyrkuwu** [comment]
You need to remove your mods folder

**Comment by eMarce1** [comment]
> You need to remove your mods folder

It didnt work

**Comment by Altf4lol** [comment]
use TL for Mc Launcher and it will work ive tried using original minecraft launcher and it didnt work

**Comment by Intrivus** [comment]
when the feather launch and done loading and full screen it crash
no crash report or anyth my memory is pro and nothing was wrong
