### ISSUE TITLE
Launching Game Failed While Downloading .jar files

### ISSUE THREAD

**Issue by knightryry** [imbreydan/Feather-Client-Installer#11]
Just Tried to install this. i had forge installed before and now its unhappy about it. I tryed to delete it but it came back with the same error and redownloaded it.
Error:
`Failed to download file.
Name: forge-1.8.9-11.15.1.2318-1.8.9.jar
URL: https://maven.minecraftforge.net/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9.jar
Filename on disk: forge-1.8.9-11.15.1.2318-1.8.9.jar
Path: C:\Users\KnightRyRy\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.8.9-11.15.1.2318-1.8.9\forge-1.8.9-11.15.1.2318-1.8.9.jar
Exists: File`

**Comment by imbreydan** [comment]
delete the "libraries" folder contained in your .minecraft

**Comment by knightryry** [comment]
That didn't work but I removed all of my mods from my mods folder and that worked.
