### ISSUE TITLE
Error: java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by Deazzy14** [imbreydan/Feather-Client-Installer#12]
I tried reinstalling forge and feather client. But I still got the same error (java.lang.NullPointerException: Initializing game) . 
How do I fix this?

**Comment by NeedlessPage819** [comment]
@imbreydan you little ｎｉｇｇｅｒ you closed this as completed just go ᴋʏꜱ ꜰᴜᴄᴋɪɴɢ ɴɪɢɢᴇʀ
