### ISSUE TITLE
fake fps

### ISSUE THREAD

**Issue by Zlud** [imbreydan/Feather-Client-Installer#3]
fps is just fake if it says 9k+ it is like 500 lmfao just fully fake

**Comment by JessePepper69** [comment]
not our problem

**Comment by Zetvue** [comment]
> not our problem

That is your problem actually. The class that does this in the original source does not spoof FPS. You are a moron.

**Comment by Zlud** [comment]
> not our problem

the actual client doesn't spoof fps so it is 🤡

**Comment by imbreydan** [comment]
> > That is your problem actually. The class that does this in the original source does not spoof FPS. You are a moron.

github must be broken because i dont see the message where anybody asked

**Comment by imbreydan** [comment]
literally hit f3 bozo
